name: Deploy Application

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

permissions:
  id-token: write
  contents: read
  pages: write  # Required for GitHub Pages deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Set environment variables (using GitHub Secrets)
      - name: Set environment variables
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "PROJECT_ID=${{ secrets.PROJECT_ID }}" >> $GITHUB_ENV
          echo "STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "MSG_SENDER_ID=${{ secrets.MSG_SENDER_ID }}" >> $GITHUB_ENV
          echo "APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
          echo "MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }}" >> $GITHUB_ENV

      # Optional: Set repository variables (if needed)
      - name: Set repository variables as environment variables
        run: |
          echo "MOVIE_URL=${{ vars.MOVIE_URL }}" >> $GITHUB_ENV
          echo "SHOW_URL=${{ vars.SHOW_URL }}" >> $GITHUB_ENV
          echo "FEED_URL=${{ vars.FEED_URL }}" >> $GITHUB_ENV
          echo "USER_URL=${{ vars.USER_URL }}" >> $GITHUB_ENV

      # Step 5: Build the Angular application
      - name: Build Angular App
        run: npm run build -- --configuration production --output-path=docs --base-href /My-Projects/EntLib

      # Step 6: Upload the artifact for GitHub Pages
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: docs/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages  # Required for GitHub Pages

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  firebase-deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 3: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }} --project entertaimentlib-ad956

